diff a/Dockerfile b/Dockerfile	(rejected hunks)
@@ -7,6 +7,7 @@
 
 # Install the Agent
 ADD https://circle-artifacts.com/gh/DataDog/docker-dd-agent-build-deb-x64/791/artifacts/0/home/ubuntu/docker-dd-agent-build-deb-x64/pkg/datadog-agent_5.7.0.git.307.b3ebdb0-1_amd64.deb /
+RUN dpkg -i /datadog-agent_5.7.0.git.307.b3ebdb0-1_amd64.deb && rm /datadog-agent_5.7.0.git.307.b3ebdb0-1_amd64.deb
 
 # Configure the Agent
 # 1. Listen to statsd from other containers
